name: FileManager
api: [3.0.0, 4.0.0]
version: 1.0.0
author: CodenameAurora
authors: [VixikHD]
main: aurora\filemanager\FileManager
description: Manage with server files in game!

commands:
  filemanager:
    description: Opens file manager form
    aliases: [fm]

permissions:
  fm:
    default: false
    children:
  fm.action:
    default: op
    children:
  fm.action.open:
    deafult: op
    description: "Allows players to open FileManager"
